CREATE TABLE p_todo (
 itodo BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 iplant BIGINT UNSIGNED NOT NULL,
 ctnt VARCHAR(30) NOT NULL,
 deadline DATETIME NOT NULL,
 created_at DATETIME DEFAULT NOW(),
 updated_at DATETIME DEFAULT NOW(),
 del_yn TINYINT(4) DEFAULT 0 CHECK (del_yn IN (0,1)),
 finish_yn TINYINT(4) DEFAULT 0 CHECK (finish_yn IN (0,1)),
 finished_at DATETIME NOT NULL,
 repeat_yn TINYINT(4) DEFAULT 0 CHECK (finish_yn IN (0,1)),
 FOREIGN KEY (iplant) REFERENCES p_plant (iplant)
);

CREATE TABLE p_plant (
 iplant BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
 nick_nm VARCHAR(20) NOT NULL,
 plant_pic VARCHAR(200) NOT NULL,
 on_date DATE NOT NULL,
 ctnt VARCHAR(50)
);

ALTER TABLE p_plant ADD nm VARCHAR(20) NOT NULL;
CREATE TABLE p_diary (
 idiary BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
 title VARCHAR(30) NOT NULL,
 ctnt VARCHAR(1000) NOT NULL,
 created_at DATETIME DEFAULT NOW(),
 pic VARCHAR(300) 
);


CREATE TABLE p_diary_pic(
 ipic BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
 idiary BIGINT UNSIGNED NOT NULL,
 pic VARCHAR (300),
 FOREIGN KEY (idiary) REFERENCES p_diary (idiary)
);

CREATE TABLE p_day (
iday BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
itodo BIGINT UNSIGNED NOT NULL,
repeat_day DATE NOT NULL,
created_at DATETIME DEFAULT NOW(),
FOREIGN KEY (itodo) REFERENCES p_todo (itodo)
);

DROP TABLE t_plant; 